name: MojAzad V3 Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: '14742923'
          packages: 'platforms;android-37.0 build-tools;37.0.0 platform-tools'

      - name: Install NDK
        run: |
          echo "y" | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" \
            --channel=0 \
            --install "ndk;29.0.14206865"

          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> "$GITHUB_ENV"

          if ! grep -q 'ndkVersion = "29.0.14206865"' \
            "${{ github.workspace }}/V2rayNG/app/build.gradle.kts"; then

            sed -i '/^android {/a\    ndkVersion = "29.0.14206865"' \
              "${{ github.workspace }}/V2rayNG/app/build.gradle.kts"
          fi

      - name: Restore libhevtun cache
        id: cache-libhevtun
        uses: actions/cache/restore@v6
        with:
          path: ${{ github.workspace }}/libs
          key: libhevtun-${{ runner.os }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh') }}

      - name: Build libhevtun
        if: steps.cache-libhevtun.outputs.cache-hit != 'true'
        run: |
          bash compile-hevtun.sh

      - name: Save libhevtun cache
        if: steps.cache-libhevtun.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: ${{ github.workspace }}/libs
          key: libhevtun-${{ runner.os }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh') }}

      - name: Copy libhevtun
        run: |
          cp -r \
            "${{ github.workspace }}/libs" \
            "${{ github.workspace }}/V2rayNG/app/"

      - name: Detect AndroidLibXrayLite version
        run: |
          cd "${{ github.workspace }}/AndroidLibXrayLite"

          CURRENT_TAG="$(git describe --tags --abbrev=0)"

          echo "AndroidLibXrayLite tag: $CURRENT_TAG"

          echo "CURRENT_TAG=$CURRENT_TAG" >>
